# Generated by Django 3.2.4 on 2021-06-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometraje', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=4)),
                ('precio', models.IntegerField()),
                ('inventario', models.IntegerField()),
                ('siGas', models.BooleanField()),
                ('siHybrido', models.BooleanField()),
                ('marca', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10)),
                ('documento', models.IntegerField()),
            ],
        ),
    ]
