# Generated by Django 3.2.4 on 2021-06-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carros',
            name='siGas',
        ),
        migrations.RemoveField(
            model_name='carros',
            name='siHybrido',
        ),
    ]
