# Generated by Django 3.2.4 on 2021-06-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_alter_clientes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='modelo',
            field=models.CharField(max_length=4, verbose_name='Año de fabricacion'),
        ),
    ]
