# Generated by Django 3.2.4 on 2021-06-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0004_alter_carros_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carros',
            name='fechaIngreso',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
