# Generated by Django 3.2.4 on 2021-06-17 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0005_carros_fechaingreso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carros',
            old_name='fechaIngreso',
            new_name='fechaIngr',
        ),
    ]
