# Generated by Django 3.2.4 on 2021-06-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0008_auto_20210617_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='ropa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('seccion', models.CharField(max_length=50)),
                ('tallas', models.IntegerField()),
                ('material', models.CharField(max_length=70)),
                ('resorteInterno', models.BooleanField()),
                ('referencia', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='carros',
        ),
    ]
