# Generated by Django 3.2.4 on 2021-06-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0010_ropa_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropa',
            name='fechaProduccion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ropa',
            name='lote',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
