# Generated by Django 3.2.4 on 2021-06-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0012_auto_20210619_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ropa',
            name='lote',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
