# Generated by Django 3.2.4 on 2021-06-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0013_alter_ropa_lote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ropa',
            options={'verbose_name': 'seccion', 'verbose_name_plural': 'seccion'},
        ),
        migrations.AddField(
            model_name='ropa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
