# Generated by Django 3.2.4 on 2021-06-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0014_auto_20210623_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ropa',
            options={'verbose_name': 'prendas', 'verbose_name_plural': 'prendas'},
        ),
        migrations.AlterField(
            model_name='ropa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='gestionPedidos'),
        ),
    ]
