# Generated by Django 3.2.4 on 2021-06-23 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0016_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ropa',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.categorias'),
        ),
    ]
