# Generated by Django 3.2.4 on 2021-06-23 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0017_alter_ropa_seccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ropa',
            old_name='seccion',
            new_name='secciones',
        ),
    ]
