# Generated by Django 3.2.4 on 2021-06-23 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0019_auto_20210623_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ropa',
            name='seccion',
        ),
    ]
