# Generated by Django 3.2.4 on 2021-06-23 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0021_ropa_seccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ropa',
            name='seccion',
        ),
    ]
