# Generated by Django 3.2.4 on 2021-06-23 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0022_remove_ropa_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropa',
            name='secciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.categorias'),
        ),
    ]
