# Generated by Django 3.2.4 on 2021-06-23 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0023_ropa_secciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name': 'categorias', 'verbose_name_plural': 'categorias'},
        ),
    ]
