# Generated by Django 3.2.4 on 2021-06-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0024_alter_categorias_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ropa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='gestionPedidos/templates/fotos'),
        ),
    ]
