# Generated by Django 3.2.4 on 2021-06-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0026_alter_ropa_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ropa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='ropa'),
        ),
    ]
